{{ if .Values.OperationsCenter.Enabled -}}
{{- if include "cloudbees-core.needs-routes" . -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: cjoc
  labels:
{{ include "cloudbees-core.labels" . | indent 4 }}
spec:
{{- if .Values.OperationsCenter.HostName }}
  host:  {{ .Values.OperationsCenter.HostName | quote }}
{{- end }}
  path: {{ include "oc.contextpath" . | quote }}
  to:
    kind: Service
    name: cjoc
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
        {{- if eq .Values.OperationsCenter.Route.tls.Enable true }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
        {{end }}
{{ include "chart.helmRouteFix" $ }}
{{- end -}}
{{- end -}}
