{{- if .Values.Hibernation.Enabled -}}
{{- if include "cloudbees-core.needs-routes" . -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: managed-master-hibernation-monitor
spec:
{{- if .Values.OperationsCenter.HostName }}
  host:  {{ .Values.OperationsCenter.HostName | quote }}
{{- end }}
  path: /hibernation
  to:
    kind: Service
    name: managed-master-hibernation-monitor
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
        {{- if eq .Values.OperationsCenter.Route.tls.Enable true }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
        {{end }}
{{ include "chart.helmRouteFix" $ }}
{{- end -}}
{{- end -}}
