{{- if .Values.Master.Enabled -}}
{{- if .Values.rbac.install -}}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: cjoc-master-role-binding
  namespace: {{ template "agents.namespace" . }}
  labels:
{{ include "cloudbees-core.labels" . | indent 4 }}
roleRef:
  apiGroup: {{ template "rbac.apiGroup" . }}
  kind: Role
  name: cjoc-agents
subjects:
- kind: ServiceAccount
  name: {{ .Values.rbac.masterServiceAccountName }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
{{- end -}}
