dependencies:
- name: nginx-ingress
  version: 1.40.2
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: nginx-ingress.Enabled
- name: ingress-nginx
  version: 2.15.0
  repository: https://kubernetes.github.io/ingress-nginx
  condition: ingress-nginx.Enabled
- name: cloudbees-sidecar-injector
  version: 2.1.0
  repository: https://charts.cloudbees.com/public/cloudbees
  condition: sidecarinjector.Enabled
